Repository kirillzyusko/react-native-keyboard-controller, pull requests merged in 2023-06, with the labels that each got.

#157 fix: use old `keyboardView` reference for removing observer
  ios/KeyboardMovementObserver.swift
Labels: 🍎 iOS, 🎯 crash

#160 docs: fix spells
  docs/versioned_docs/version-1.0.0/guides/first-animation.md
  docs/versioned_docs/version-1.4.0/guides/first-animation.md
  docs/versioned_docs/version-1.5.0/guides/first-animation.md
Labels: documentation

#158 chore: release v1.5.4
  FabricExample/ios/Podfile.lock
  example/ios/Podfile.lock
  package.json
Labels: release

#161 feat: markdown lint for docs
  .github/workflows/verify-docs.yml
  docs/.markdownlint.yaml
  docs/README.md
  docs/blog/2022-09-22-fabric/index.md
  docs/blog/2022-10-15-new-hook/index.md
  docs/docs/api/hooks/use-keyboard-animation.md
  docs/docs/api/hooks/use-reanimated-keyboard-animation.md
  docs/docs/api/keyboard-controller-view.md
  docs/docs/api/keyboard-controller.md
  docs/docs/api/keyboard-events.md
  docs/docs/api/keyboard-gesture-area.md
  docs/docs/api/keyboard-provider.md
  docs/docs/guides/building-own-hook.md
  docs/docs/guides/compatibility.md
  docs/docs/installation.md
  docs/docs/recipes/architecture.md
  docs/package.json
  docs/src/pages/markdown-page.md
  docs/versioned_docs/version-1.0.0/api/hooks/use-keyboard-animation.md
  docs/versioned_docs/version-1.0.0/api/hooks/use-reanimated-keyboard-animation.md
  docs/versioned_docs/version-1.0.0/api/keyboard-controller-view.md
  docs/versioned_docs/version-1.0.0/api/keyboard-controller.md
  docs/versioned_docs/version-1.0.0/api/keyboard-events.md
  docs/versioned_docs/version-1.0.0/api/keyboard-provider.md
  docs/versioned_docs/version-1.0.0/guides/building-own-hook.md
  docs/versioned_docs/version-1.0.0/guides/compatibility.md
  docs/versioned_docs/version-1.0.0/guides/first-animation.md
  docs/versioned_docs/version-1.0.0/installation.md
  docs/versioned_docs/version-1.0.0/recipes/architecture.md
  docs/versioned_docs/version-1.4.0/api/hooks/use-keyboard-animation.md
  docs/versioned_docs/version-1.4.0/api/hooks/use-reanimated-keyboard-animation.md
  docs/versioned_docs/version-1.4.0/api/keyboard-controller-view.md
  docs/versioned_docs/version-1.4.0/api/keyboard-controller.md
  docs/versioned_docs/version-1.4.0/api/keyboard-events.md
  docs/versioned_docs/version-1.4.0/api/keyboard-provider.md
  docs/versioned_docs/version-1.4.0/guides/building-own-hook.md
  docs/versioned_docs/version-1.4.0/guides/compatibility.md
  docs/versioned_docs/version-1.4.0/guides/first-animation.md
  docs/versioned_docs/version-1.4.0/installation.md
  docs/versioned_docs/version-1.4.0/recipes/architecture.md
  docs/versioned_docs/version-1.5.0/api/hooks/use-keyboard-animation.md
  docs/versioned_docs/version-1.5.0/api/hooks/use-reanimated-keyboard-animation.md
  docs/versioned_docs/version-1.5.0/api/keyboard-controller-view.md
  docs/versioned_docs/version-1.5.0/api/keyboard-controller.md
  docs/versioned_docs/version-1.5.0/api/keyboard-events.md
  docs/versioned_docs/version-1.5.0/api/keyboard-gesture-area.md
  docs/versioned_docs/version-1.5.0/api/keyboard-provider.md
  docs/versioned_docs/version-1.5.0/guides/building-own-hook.md
  docs/versioned_docs/version-1.5.0/guides/compatibility.md
  docs/versioned_docs/version-1.5.0/guides/first-animation.md
  docs/versioned_docs/version-1.5.0/installation.md
  docs/versioned_docs/version-1.5.0/recipes/architecture.md
  docs/yarn.lock
Labels: documentation, CI, refactor

#162 docs: appearance -> movement
  README.md
  docs/src/components/HomepageFeatures/index.tsx
Labels: documentation

#164 docs: better seo
  docs/blog/2022-06-22-welcome/index.mdx
  docs/blog/2022-09-22-fabric/index.md
  docs/blog/2022-10-15-new-hook/index.md
  docs/blog/2023-04-10-interactive-keyboard/index.mdx
  docs/docs/api/hooks/use-keyboard-animation.md
  docs/docs/api/hooks/use-keyboard-handler/index.mdx
  docs/docs/api/hooks/use-reanimated-keyboard-animation.md
  docs/docs/api/keyboard-controller-view.md
  docs/docs/api/keyboard-controller.md
  docs/docs/api/keyboard-events.md
  docs/docs/api/keyboard-gesture-area.md
  docs/docs/api/keyboard-provider.md
  docs/docs/guides/building-own-hook.md
  docs/docs/guides/compatibility.md
  docs/docs/guides/first-animation.md
  docs/docs/guides/interactive-keyboard.md
  docs/docs/installation.md
  docs/docs/recipes/architecture.md
  docs/docs/recipes/jest-testing-guide.md
  docs/docs/recipes/platform-differences.md
  docs/versioned_docs/version-1.5.0/api/hooks/use-keyboard-animation.md
  docs/versioned_docs/version-1.5.0/api/hooks/use-keyboard-handler/index.mdx
  docs/versioned_docs/version-1.5.0/api/hooks/use-reanimated-keyboard-animation.md
  docs/versioned_docs/version-1.5.0/api/keyboard-controller-view.md
  docs/versioned_docs/version-1.5.0/api/keyboard-controller.md
  docs/versioned_docs/version-1.5.0/api/keyboard-events.md
  docs/versioned_docs/version-1.5.0/api/keyboard-gesture-area.md
  docs/versioned_docs/version-1.5.0/api/keyboard-provider.md
  docs/versioned_docs/version-1.5.0/guides/building-own-hook.md
  docs/versioned_docs/version-1.5.0/guides/compatibility.md
  docs/versioned_docs/version-1.5.0/guides/first-animation.md
  docs/versioned_docs/version-1.5.0/guides/interactive-keyboard.md
  docs/versioned_docs/version-1.5.0/installation.md
  docs/versioned_docs/version-1.5.0/recipes/architecture.md
  docs/versioned_docs/version-1.5.0/recipes/jest-testing-guide.md
  docs/versioned_docs/version-1.5.0/recipes/platform-differences.md
Labels: documentation

#167 fix: check if `jsThread` is not null
  ios/KeyboardControllerView.mm
  ios/KeyboardControllerViewManager.swift
Labels: 🍎 iOS, 🎯 crash

#169 chore: release v1.5.5
  FabricExample/ios/Podfile.lock
  example/ios/Podfile.lock
  package.json
Labels: release

#170 refactor: move `interpolate` function to Extensions
  ios/Extensions.swift
  ios/KeyboardController.xcodeproj/project.pbxproj
  ios/KeyboardMovementObserver.swift
Labels: 🍎 iOS, refactor

#171 fix: Add compatibility with native iOS navigation
  src/animated.tsx
Labels: 🐛 bug, 🍎 iOS

#172 chore: release 1.5.6
  FabricExample/ios/Podfile.lock
  example/ios/Podfile.lock
  package.json
Labels: release

#180 refactor: support for non-transitive R-classes
  android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt
Labels: 🤖 android, refactor

#181 chore: set library namespace in build script
  android/build.gradle
Labels: 🤖 android, refactor

#179 chore: react-native 0.71.11
  FabricExample/.ruby-version
  FabricExample/Gemfile
  FabricExample/ios/Podfile
  FabricExample/ios/Podfile.lock
  FabricExample/package.json
  FabricExample/yarn.lock
  example/.ruby-version
  example/Gemfile
  example/ios/Podfile.lock
  example/package.json
  example/yarn.lock
  package.json
  src/animated.tsx
  yarn.lock
Labels: deps update

#178 fix: native alert crash
  ios/KeyboardMovementObserver.swift
Labels: 🍎 iOS, 🎯 crash

#182 chore: release 1.5.7
  FabricExample/ios/Podfile.lock
  example/ios/Podfile.lock
  package.json
Labels: release

#187 fix: casting UIView to UIView always succeeds
  ios/KeyboardMovementObserver.swift
Labels: 🍎 iOS, refactor

#186 fix: ignore invalid values from KVO
  ios/KeyboardMovementObserver.swift
Labels: 🐛 bug, 🍎 iOS, 👆 interactive keyboard
