Repository kirillzyusko/react-native-keyboard-controller, pull requests merged in 2023-11, with the labels that each got.

#261 docs: blogpost 1.9.0
  docs/blog/2023-11-01-new-features-achieved-milestones/index.mdx
Labels: documentation

#260 chore: release 1.9.0
  FabricExample/ios/Podfile.lock
  example/ios/Podfile.lock
  package.json
Labels: release

#268 fix: compare size in `onApplyWindowInsets`
  android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt
Labels: 🐛 bug, 🤖 android

#269 chore: release 1.9.1
  FabricExample/ios/Podfile.lock
  example/ios/Podfile.lock
  package.json
Labels: release

#273 chore: release 1.9.2
  FabricExample/ios/Podfile.lock
  example/ios/Podfile.lock
  package.json
Labels: release

#276 chore: release 1.9.3
  FabricExample/ios/Podfile.lock
  example/ios/Podfile.lock
  package.json
Labels: release

#278 fix: typo on README.md
  README.md
  docs/docs/installation.mdx
  docs/versioned_docs/version-1.9.0/installation.mdx
Labels: documentation

#277 fix: race condition in `onApplyWindowInsets`
  android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt
Labels: 🐛 bug, 🤖 android

#280 docs: add a note about `useResizeMode` hook
  docs/docs/guides/building-own-hook.md
  docs/versioned_docs/version-1.9.0/guides/building-own-hook.md
Labels: documentation

#279 chore: release 1.9.4
  FabricExample/ios/Podfile.lock
  example/ios/Podfile.lock
  package.json
Labels: release

#282 refactor: rename `FocusedInputLayoutObserver` -> `FocusedInputObserver`
  android/src/main/java/com/reactnativekeyboardcontroller/listeners/FocusedInputObserver.kt
  android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt
  ios/KeyboardController.xcodeproj/project.pbxproj
  ios/observers/FocusedInputObserver.swift
  ios/views/KeyboardControllerView.mm
  ios/views/KeyboardControllerViewManager.swift
Labels: 🤖 android, 🍎 iOS, refactor

#284 fix: race condition in `useSmoothKeyboardHandler`
  FabricExample/src/components/AwareScrollView/useSmoothKeyboardHandler.ts
  example/src/components/AwareScrollView/useSmoothKeyboardHandler.ts
Labels: 🤖 android, example
