Repository kirillzyusko/react-native-keyboard-controller, pull requests merged in 2025-05, with the labels that each got.

#932 Update troubleshooting.md
  docs/versioned_docs/version-1.17.0/troubleshooting.md
Labels: documentation

#934 fix: CI for docs
  cspell.json
  docs/docs/troubleshooting.md
  docs/versioned_docs/version-1.17.0/troubleshooting.md
Labels: documentation

#939 docs: improvements for `KeyboardGestureArea` view
  docs/docs/api/keyboard-gesture-area.md
  docs/versioned_docs/version-1.16.0/api/keyboard-gesture-area.md
  docs/versioned_docs/version-1.17.0/api/keyboard-gesture-area.md
Labels: documentation, 👆 interactive keyboard

#941 docs: update tip for ninja path
  docs/docs/troubleshooting.md
  docs/versioned_docs/version-1.17.0/troubleshooting.md
Labels: documentation

#942 docs: better JSDoc
  .eslintrc.cjs
  package.json
  src/animated.tsx
  src/bindings.ts
  src/components/KeyboardAvoidingView/index.tsx
  src/components/KeyboardAwareScrollView/index.tsx
  src/components/KeyboardAwareScrollView/useSmoothKeyboardHandler.ts
  src/components/KeyboardStickyView/index.tsx
  src/components/KeyboardToolbar/index.tsx
  src/context.ts
  src/hooks/index.ts
  src/hooks/useKeyboardState/index.ts
  src/internal.ts
  src/module.ts
  src/monkey-patch.android.ts
  src/types/hooks.ts
  src/types/index.ts
  src/types/internal.ts
  src/types/module.ts
  src/types/views.ts
  src/views/OverKeyboardView/index.tsx
  yarn.lock
Labels: documentation

#943 fix: e2e tests (on iOS 16)
  e2e/kit/006-interactive-keyboard.e2e.ts
Labels: CI, e2e

#944 chore: release 1.17.2
  FabricExample/ios/Podfile.lock
  example/ios/Podfile.lock
  package.json
Labels: release

#948 fix: rely on screen dimensions instead of window dimensions
  src/hooks/useWindowDimensions/index.ts
Labels: 🐛 bug, 🍎 iOS

#950 fix: keep shadow nodes in sync
  FabricExample/src/screens/Examples/AwareScrollViewStickyFooter/index.tsx
  android/src/main/java/com/reactnativekeyboardcontroller/extensions/ThemedReactContext.kt
  android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt
  example/src/screens/Examples/AwareScrollViewStickyFooter/index.tsx
Labels: 🐛 bug, 🤖 android, KeyboardStickyView 🩹, KeyboardToolbar

#952 fix: support dynamic `bottomOffset` for `KeyboardAwareScrollView`
  src/components/KeyboardAwareScrollView/index.tsx
Labels: 🐛 bug, KeyboardAwareScrollView 📜

#959 docs: enhance `useKeyboardState` SEO
  docs/docs/api/hooks/keyboard/use-keyboard-state.mdx
  docs/versioned_docs/version-1.17.0/api/hooks/keyboard/use-keyboard-state.mdx
Labels: documentation

#958 chore: release 1.17.3
  FabricExample/ios/Podfile.lock
  example/ios/Podfile.lock
  package.json
Labels: release
