Repository kirillzyusko/react-native-keyboard-controller, pull requests merged in 2025-04, with the labels that each got.

#892 docs: rephrase `translucent` StatusBar handling on Android for `keyboardVerticalOffset`
  docs/docs/api/components/keyboard-avoiding-view.mdx
  docs/src/components/KeyboardVerticalOffset/kvo-dark.svg
  docs/src/components/KeyboardVerticalOffset/kvo-light.svg
  docs/versioned_docs/version-1.16.0/api/components/keyboard-avoiding-view.mdx
Labels: documentation

#895 docs: add Rainbow to "Trusted by" section
  docs/src/pages/index.tsx
Labels: documentation

#902 fix: set delegate to all `UITextView`
  ios/KeyboardController-Bridging-Header.h
  ios/objc/UITextView+DelegateManager.h
  ios/objc/UITextView+DelegateManager.m
  ios/observers/FocusedInputObserver.swift
Labels: 🐛 bug, 🍎 iOS, focused input 📝

#898 feat: `KeyboardStickyView` using plain Animated
  src/components/KeyboardStickyView/index.tsx
Labels: refactor

#907 fix: `useKeyboardState` tweaks
  docs/docs/api/hooks/keyboard/use-keyboard-state.mdx
  docs/docs/api/keyboard-controller.md
  jest/index.js
  src/hooks/useKeyboardState/index.ts
  src/module.ts
  src/types.ts
Labels: documentation, enhancement

#906 docs: blogpost for `1.17` release
  docs/blog/2025-04-09-release-1-17/index.mdx
  docs/blog/2025-04-09-release-1-17/use-keyboard-state.png
Labels: documentation

#913 fix: `OverKeyboardView` crash
  android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/OverKeyboardViewGroup.kt
Labels: 🤖 android, 🎯 crash, OverKeyboardView

#919 fix: skipped snapshot test
  FabricExample/__tests__/__snapshots__/components-rendering.spec.tsx.snap
  FabricExample/__tests__/components-rendering.spec.tsx
  example/__tests__/__snapshots__/components-rendering.spec.tsx.snap
  example/__tests__/components-rendering.spec.tsx
Labels: tests

#903 docs: `forwardRef` for `FlashList`+`renderScrollComponent`
  docs/docs/api/components/keyboard-aware-scroll-view.mdx
  docs/versioned_docs/version-1.16.0/api/components/keyboard-aware-scroll-view.mdx
  docs/versioned_docs/version-1.17.0/api/components/keyboard-aware-scroll-view.mdx
Labels: documentation

#900 fix: Square payment SDK integration
  cspell.json
  ios/delegates/KCTextInputCompositeDelegate.swift
  ios/observers/FocusedInputObserver.swift
Labels: 🍎 iOS, 🎯 crash, focused input 📝

#921 fix: disabling KeyboardAwareScrollView didn't prevent useAnimatedStyle flickering
  src/components/KeyboardAwareScrollView/index.tsx
Labels: 🐛 bug, KeyboardAwareScrollView 📜

#912 fix: findNodeHandle on the web platform
  src/components/KeyboardAwareScrollView/index.tsx
  src/internal.ts
  src/utils/findNodeHandle/index.native.ts
  src/utils/findNodeHandle/index.ts
Labels: 🎯 crash, 🌐 web

#918 fix: `OverKeyboardView` rotation (fabric)
  android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/OverKeyboardViewGroup.kt
Labels: 🐛 bug, 🤖 android, 🏭 fabric, OverKeyboardView

#925 docs: components overview
  docs/blog/2025-04-09-release-1-17/index.mdx
  docs/docs/guides/compatibility.md
  docs/docs/guides/components-overview.mdx
  docs/versioned_docs/version-1.17.0/guides/compatibility.md
  docs/versioned_docs/version-1.17.0/guides/components-overview.mdx
Labels: documentation
